### ISSUE TITLE
Pestañas de ticketera (Abierto, Respondió, etc)

### ISSUE THREAD

**Issue by fernandojoelale** [icsred/Help-Desk#4]
Permite al agente visualizar los tickets según el estado de los mismos:
- Abierto: Muestra los tickets que ningún agente ha tomado o que están tomados y tuvieron alguna respuesta/comentario del solicitante
- Respondió: Muestra los tickets que tienen como estado "Procesando" o "Implementado", cuyas últimas respuestas fueron del agente
- Mis tickets: Disposición de los tickets tomados por el agente
- Vencido: Tickets que estuvieron cinco días hábiles sin ser respondidos y aún se está buscando su solución
- Cerrado: Tickets resueltos y cerrados

Se debe mostrar entre paréntesis el número de tickets en cada sección.
Por ejemplo:
Abierto (7)          Respondió (10)          Mis tickets (5)          Vencido (9)          Cerrado (3500)

- [x] Agrupar y visualizar por estado

- [x] Marcar la sección actual en la que se encuentra el agente

- [x] Actualizar el número de tickets automáticamente (si pasan a cerrado, a respondido, etc)

- [ ] #22

**Comment by giovanni-marte** [comment]
Este issue se pudo completar con los siguientes commits: https://github.com/icsred/Help-Desk/commit/824fad211d9407cf29bfb3e64cb3f59af7ddd40e https://github.com/icsred/Help-Desk/commit/04a59420cc5323fe6f6f18dae540b8ce658db5cf https://github.com/icsred/Help-Desk/commit/a8bd3e61da80625bdae589da138588cf0c8eb33d
