### ISSUE TITLE
Renderizar tickets en frontend desde BD (front y back)

### ISSUE THREAD

**Issue by fernandojoelale** [icsred/Help-Desk#9]
Esta tarea permite cargar los tickets de la base de datos en el panel del agente.

- [x] Formatear fecha

**Comment by giovanni-marte** [comment]
Para implementar esta característica se tuvieron que realizar los componentes principales y se hizo uso del hook useEffect para cargar los tickets en la primera carga de la página. 
https://github.com/icsred/Help-Desk/commit/67474116305b8fb2603133f5f6c3a48b9f0fc983
